select * from INFORMATION_SCHEMA.TABLES

select * from INFORMATION_SCHEMA.COLUMNS

-- Explore countries our customers come from

select distinct country from dbo.[gold.dim_customers]

-- Explore product categories

select distinct category, subcategory, product_name
from dbo.[gold.dim_products]
order by 1,2,3

-- Find the first and last order date and total no.of years

select MIN(order_date) as First_order_date,
MAX(order_date) as Last_order_date,
DATEDIFF (year,min(order_date),max(order_date)) as Range_of_years
from [gold.fact_sales]

-- Find the Oldest and Youngest Customer

select min([birthdate]) as oldest_birthdate,
DATEDIFF(year, MIN(birthdate), getdate ()) as oldest_age,
max([birthdate]) as youngest_birthdate,
DATEDIFF(year, MAX(birthdate), getdate ()) as youngest_age
from [dbo].[gold.dim_customers]

-- Generating a report for finding all key metrics of the business

select 'Total sales' as measure_name, SUM(sales_amount) as measure_value from [dbo].[gold.fact_sales]
union all
select 'Total quantity', SUM([quantity]) from [dbo].[gold.fact_sales]
union all
select 'Avg price', AVG(price) from [dbo].[gold.fact_sales]
union all
select 'Total no of orders',COUNT(DISTINCT([order_number])) from [dbo].[gold.fact_sales]
union all
select 'Total no of products',COUNT([product_number]) from [dbo].[gold.dim_products]
union all
select 'Total no of customers',COUNT([customer_key]) from [dbo].[gold.dim_customers]
union all
select 'Total customers', COUNT(distinct([customer_key])) from [dbo].[gold.fact_sales]

-- Find total customers by country

select country, count(customer_key) as total_customers
from [dbo].[gold.dim_customers]
group by country
order by total_customers desc

-- Find total customers by gender 

select gender, COUNT(customer_key) as total_customers
from [dbo].[gold.dim_customers]
group by gender
order by total_customers desc

-- Find the total products by category

select category, count(product_key) as total_products
from [dbo].[gold.dim_products]
group by category
order by total_products desc

-- Find the average costs by each category

select category, AVG(cost) as avg_cost
from [dbo].[gold.dim_products]
group by category
order by avg_cost desc

-- Find the total revenue generated by each category 

select p.category, SUM(f.sales_amount) as total_revenue 
from [dbo].[gold.fact_sales] f
join [dbo].[gold.dim_products] p 
on f.product_key = p.product_key
group by p.category
order by total_revenue desc

-- Find the total revenue generated by each customer

select c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) as total_revenue
from [dbo].[gold.fact_sales] f
join [dbo].[gold.dim_customers] c 
on f.customer_key = c.customer_key 
group by c.customer_key, c.first_name, c.last_name
order by total_revenue desc

-- Find the distribution of sold items across countries

select c.country, SUM(f.quantity) as total_sold_items
from [dbo].[gold.fact_sales] f 
join [dbo].[gold.dim_customers] c 
on f.customer_key = c.customer_key
group by c.country
order by total_sold_items desc

-- Find the five products that generate the highest revenue

select top 5 p.product_name, SUM(f.sales_amount) as total_revenue 
from dbo.[gold.fact_sales] f
join dbo.[gold.dim_products] p 
on f.product_key = p.product_key 
group by p.product_name
order by total_revenue desc

-- What are the five worst performing products in terms of sales?

select top 5 p.product_name, SUM(f.sales_amount) as total_revenue 
from dbo.[gold.fact_sales] f
join dbo.[gold.dim_products] p 
on f.product_key = p.product_key 
group by p.product_name
order by total_revenue desc

-- Find the top 10 customer who have generated the highest revenue

select top 10 c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) as total_revenue
from [dbo].[gold.fact_sales] f
join [dbo].[gold.dim_customers] c 
on f.customer_key = c.customer_key 
group by c.customer_key, c.first_name, c.last_name
order by total_revenue desc

-- Find the five customers with the fewest orders 

select top 5 c.customer_key, c.first_name, c.last_name, count(f.order_number) as no_of_orders
from [dbo].[gold.fact_sales] f
join [dbo].[gold.dim_customers] c 
on f.customer_key = c.customer_key 
group by c.customer_key, c.first_name, c.last_name
order by no_of_orders 

-- What percentage of customers made repeat purchases?

select 
count(distinct case when repeat_purchase = 1 then customer_key end) * 100.0 / count(distinct customer_key) as repeat_purchase_percentage
from (
  select customer_key, 
  case when count(order_number) > 1 then 1 else 0 end as repeat_purchase
  from dbo.[gold.fact_sales]
  group by customer_key
)t

-- Which country has the highest sales per capita?

select c.country, 
SUM(f.sales_amount) / COUNT(distinct c.customer_key) as sales_per_capita
from dbo.[gold.fact_sales] f
join dbo.[gold.dim_customers] c on f.customer_key = c.customer_key
group by c.country
order by sales_per_capita desc

-- What is the correlation between the price of products and the quantity sold?

select p.product_name, f.price, SUM(f.quantity) as total_quantity_sold
from dbo.[gold.fact_sales] f
join dbo.[gold.dim_products] p on f.product_key = p.product_key
group by p.product_name, f.price
order by total_quantity_sold desc



